version: "3"

tasks:
  proto:
    desc: "Generate Go gRPC code from protobuf definition"
    cmds:
      - >
        protoc -I proto
        proto/authorization-service/authorization-service.proto
        --go_out=./gen/go --go_opt=paths=source_relative
        --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative

  clean:
    desc: "Remove generated protobuf code"
    cmds:
      - rm -rf gen/go