version: "3"

tasks:
  proto:
    desc: "Generate Go gRPC code from all protobuf files"
    cmds:
      - >
        protoc
        -I proto
        --go_out=./gen/go --go_opt=paths=source_relative
        --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
        $(find proto/authorization-service -name "*.proto")

  clean:
    desc: "Remove generated protobuf code"
    cmds:
      - rm -rf gen/go